# Generated by Django 6.0.2 on 2026-02-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('unit_name', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('is_medal_event', models.BooleanField(default=False)),
                ('competitors_json', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('competitors', models.ManyToManyField(blank=True, related_name='events', to='schedule.country')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.discipline')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='schedule.venue')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
